id: I377F4F46
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-963c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 11:36:17.749266+00:00
last_modified: 2023-09-26 11:36:17.749274+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W11886
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW11886
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་རྣམ་བཤད་དགོངས་པ་ངེས་པར་གསལ་བ།
  languages:
  - bo
  author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.967802307718289
  ocr_word_median_confidence_index: 0.99962315
bases:
  I1KG1822:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1822
      total_pages: 451
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1822.txt
    statistics:
      ocr_word_median_confidence_index: 0.99962315
      ocr_word_mean_confidence_index: 0.967802307718289
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
